#! /usr/bin/env bash

git remote remove gitee 2>/dev/null
git remote add gitee git@gitee.com:static-build/tesseract.git
git push gitee main

git remote remove github 2>/dev/null
git remote add github git@github.com:static-build/tesseract.git
git push github main
